### ISSUE TITLE
Tesseract

### ISSUE THREAD

**Issue by retokromer** [varenc/homebrew-ffmpeg#11]
There are now two flavours of Tesseract: [tessseract](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tesseract.rb) and [tesseract-lang](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tesseract-lang.rb). I guess we should allow both:
- `--with-tesseract` which comes only with English
- `--with-tesseract-lang` which enables support for other languages

**Comment by slhck** [comment]
Do we actually have to do anything? Our formula already contains the tesseract dependency if the option is specified. The second formula (tesseract-lang) installs tesseract as a dependency, and users can add that via Homebrew itself.

**Comment by retokromer** [comment]
I guess, it would be useful to add `tesseract-lang` as additional option, because this was the previous behaviour. That way one could choose the option that fits his/her purpose.

**Comment by slhck** [comment]
Hm. Perhaps I don't understand the real benefit. The user could do:

```
brew install varenc/ffmpeg/ffmpeg --with-tesseract
brew install tesseract-lang
```

If we included a `--with-tesseract-lang` option, it wouldn't make any differences in how ffmpeg is compiled, and the user would not be free to add or remove `tesseract-lang` at any point, as his or her ffmpeg installation would always require it, even though it's just extra data that can be safely removed.

**Comment by retokromer** [comment]
Exactly! The end user needs a new, additional step, in comparison to the situation before Homebrew banned the options. That’s what I would like to avoid.

This is not blocking on my side and I suggest that Chris choose.

**Comment by slhck** [comment]
The problem I see is the following: `--with-tesseract-lang` would be an option for our formula. so enabling the option would cause all builds of our ffmpeg to require not only `tesseract`, but also require `tesseract-lang` to be present and installed.

Since `tesseract-lang` is actually a separate package, it can – at any time – be installed or uninstalled without impacting other formulae – this is the normal Homebrew-core behavior.

If we included the option, the user could not choose to uninstall the `tesseract-lang` formula, without having to reinstall (i.e., re-compile) `ffmpeg` for no real reason. We would thus be creating a hard dependency that is not needed, since the user could (and should, IMO) simply install the `tesseract-lang` formula separately, which could be added/removed independently of ffmpeg.

I know this is an extra step, but I'd like to not bake in too many workarounds for standard Homebrew behavior. I am not super passionate about it, but I think that enabling the option would somehow “mess” with what Homebrew's default behavior is at the moment.

**Comment by retokromer** [comment]
I’m not sure I understand you correctly. My proposal is to give **_in addition_** to `--with-tesseract` also the possibility to choose `--with-tesseract-lang`. That way both become possible: only English or the full library.

**Comment by slhck** [comment]
The proposal is clear to me, but the problem is, let's say I install `brew install ffmpeg --with-tesseract --with-tesseract-lang`. What if I didn't want the extra package anymore? I'd have to do a `brew reinstall` of the formula. Whereas with "normal" Homebrew behavior, all I'd have to do is `brew uninstall tesseract-lang`, which would not impact the ffmpeg installation and therefore not require re-compilation.

**Comment by retokromer** [comment]
>I'd have to do a `brew reinstall` of the formula.

Indeed, the same as you have to do if you wish to drop Tesseract… It would just be the same behaviour as we had before the Homebrew maintainers decided to ban the options, or am I missing something?

As said, this is not blocking on my side.

**Comment by slhck** [comment]
Hm, to me it seems that this causes different behavior, in that we are "masquerading" an actual formula as an option, and that we introduce a dependency (with reinstallation as a consequence) that would not be necessary. Say I want to save space, and I only want to remove the language data; then I didn't have to re-compile.

But I'm probably also splitting hairs on this. I suggest @varenc provides his opinion so we can decide :)

**Comment by retokromer** [comment]
Yet you are **_not_** obliged to install «my» way, «your» way would coexist… any way.

**Comment by slhck** [comment]
That's true, I did not consider that.

**Comment by varenc** [comment]
Ah this does seem like a tricky situation.  I don't love that `tesseract-lang` would become a required dependency for our ffmpeg formula, even though just keeping `tesseract` around would be fine.  I worry that a `--with-tesseract-lang` option might be confusing, though people that opt for this formula are probably a bit more savvy than average.

What about just keeping `tesseract` and adding an info message for users using installing `tesseract` that informs them of `tesseract-lang`?  I  just tried this out and unfortunately, messages like that get shown during the install instead of at the end like caveats, but I don't think there's a way to add a programmatically determined caveat.  Made a pull request of what that could look like at #18

**Comment by retokromer** [comment]
As said, I would like to add an **_additional option_** (not a required one) for those people who use daily Tesseract with FFmpeg to extract cast & credits, subtitles and intertitles from the image. 40–50 of our archival clients use this possibility daily. During the last years I have given for the CCAAA member organisations (e.g. AMIA, FIAF, IASA, SEAPAVAA) many trainings on FFmpeg, always including how to use Tesseract to automate this in their workflows. It would be an option, like `--with-tesseract`, which just provides the functionality that this option had… before its castration!

Yet I am in the minority and give up.
